DROP TABLE IF EXISTS PRODUCTS;
 
CREATE TABLE PRODUCTS (
ID INT AUTO_INCREMENT  PRIMARY KEY,
NAME VARCHAR(250) NOT NULL,
PRICE DECIMAL(10,2) NOT NULL,
MFG_DATE DATE NOT NULL,
EXP_DATE DATE);

INSERT INTO PRODUCTS (NAME, PRICE, MFG_DATE, EXP_DATE) VALUES ('T-Shirt', 499, TO_DATE('2019-01-10', 'yyyy-MM-DD'), NULL);
INSERT INTO PRODUCTS (NAME, PRICE, MFG_DATE, EXP_DATE) VALUES ('Jeans', 1199, TO_DATE('2019-02-15', 'yyyy-MM-DD'), NULL);
INSERT INTO PRODUCTS (NAME, PRICE, MFG_DATE, EXP_DATE) VALUES ('Rain Coat', 599, TO_DATE('2019-03-11', 'yyyy-MM-DD'), NULL);
INSERT INTO PRODUCTS (NAME, PRICE, MFG_DATE, EXP_DATE) VALUES ('Biscuits', 25, TO_DATE('2019-05-20', 'yyyy-MM-DD'), TO_DATE('2019-08-19', 'yyyy-MM-DD'));
INSERT INTO PRODUCTS (NAME, PRICE, MFG_DATE, EXP_DATE) VALUES ('Chocolates', 100, TO_DATE('2019-06-30', 'yyyy-MM-DD'), TO_DATE('2019-09-30', 'yyyy-MM-DD'));

--create table persistent_logins(username varchar(50) not null, series varchar(64) primary key, token varchar(64) not null, last_used timestamp not null);